hw.01_task.05v3 : hw.01_task.05v3.o stack.o
	g++ hw.01_task.05v3.o stack.o -o hw.01_task.05v3

hw.01_task.05v3.o : hw.01_task.05v3.cpp stack.h
	g++ -c hw.01_task.05v3.cpp

stack.o : stack.cpp stack.h
	g++ -c stack.cpp


